### ISSUE TITLE
服务无法获取token信息

### ISSUE THREAD

**Issue by yang22zhang** [DTeam-Top/dgate#11]
配置url无需验证登录(即login->only不包含相应链接)， 当用户已登陆， 无法获取相应token信息

**Comment by foxgem** [comment]
https://github.com/DTeam-Top/dgate/blob/master/docs/user_guide.md#%E6%AF%8F%E4%B8%AA%E8%AF%B7%E6%B1%82%E7%9A%84%E9%99%84%E5%8A%A0%E5%8F%82%E6%95%B0，参见此文档

**Comment by foxgem** [comment]
关于JWT Token传递到后端服务的方式已经增强：只要HTTP Request Header中有Auth头，且是dgate签发的jwt token，dgate就会将其传递给后端服务。
