### ISSUE TITLE
是否考虑优化断路器的日志

### ISSUE THREAD

**Issue by abcfy2** [DTeam-Top/dgate#13]
目前断路器的日志属于`INFO`级别，并且输出过于频繁，会产生大量的日志，十分吵，并且极容易冲掉有用的日志信息。

考虑优化断路器的日志输出，仅仅在断路器状态变化时打印`INFO`级别日志，原本的输出信息考虑放在`DEBUG`级别。

**Comment by foxgem** [comment]
引入了Logback，其日志级别可根据环境变量设置。参见[这里](https://github.com/DTeam-Top/dgate/blob/master/docs/user_guide.md#日志级别)
