### ISSUE TITLE
mock建议可以反映多种情况

### ISSUE THREAD

**Issue by lorispy** [DTeam-Top/dgate#4]
正常情况，一个接口会有多种返回，比如正常和异常返回。有时正常返回，不同的参数返回结果也有差别
调试时每次修改接口返回内容比较麻烦，
建议可以配置多种返回，可指定返回哪种
这样在调试时就可以模拟多种情况了。
mock也可以直接作为接口文档使用了。

**Comment by foxgem** [comment]
对于Mock而言，可以采用闭包来完成这种需求，参见文档：

> 若statusCode或payload本身是一个闭包，则dgate会将它们的返回值作为结果返回，这在excepted为一个动态值时非常有用，参见【Mock JWT Token】的例子。
