### ISSUE TITLE
关于通过JWTtoken验证登录的安全问题

### ISSUE THREAD

**Issue by yang22zhang** [DTeam-Top/dgate#6]
目前登录验证单单是通过判断token是否过期进行的, 便会存在如下场景:
     
攻击者解析token获取token组成规则(token中的key->id为用户id),  修改token中的id, 重新生成未过期的token, 利用新的token, 便可模拟任何用户操作, 从而进行攻击.

现在能否规避此问题?

**Comment by foxgem** [comment]
之前dgate的jwt产生所需密钥被包含在dgate的fatjar中，同时上传到了github上，有存在伪造token的风险。

现已将原来源码中自带的密钥文件转移到test/resources中，仅供测试使用。

在产品环境下，需要自己生成密钥，并通过环境变量设置。只有妥善保管好密钥文件，同时结合SSL，基本排除了伪造token的可能性，规避了以上问题。

请参见[文档的JWT Token小节](https://github.com/DTeam-Top/dgate/blob/master/docs/user_guide.md#jwt-token)
